# SPDX-FileCopyrightText: 2025 Matthieu Gallien <matthieu_gallien@yahoo.fr>
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "musicmanager"
SPDX-PackageSupplier = "Matthieu Gallien <matthieu_gallien@yahoo.fr>"
SPDX-PackageDownloadLocation = "https://github.com/mgallien/MusicManagerNextcloud"

[[annotations]]
path = [".gitattributes", ".github/**", ".editorconfig", "babel.config.cjs", ".php-cs-fixer.dist.php", "package-lock.json", "package.json", "composer.json", "composer.lock", "stylelint.config.cjs", ".eslintrc.cjs", ".gitignore", ".jshintrc", ".l10nignore", "action/.gitignore", "action/package.json", "action/package-lock.json", "action/dist/index.js", "tests/**", "psalm.xml", "cypress/.env", "cypress/.eslintrc.js", "cypress/docker-compose.yml", "cypress/plugins/index.js", "cypress/tsconfig.json", "cypress.config.ts", "vendor-bin/**/composer.json", "stylelint.config.cjs", "vendor-bin/**/composer.lock", ".tx/config", "webpack.config.js", "tsconfig.json", "vite.config.ts", "js/vendor.LICENSE.txt", "krankerl.toml", ".npmignore", "cypress/fixtures/**", "postcss.config.cjs", "cypress/dockerNode.ts", "jest.config.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["openapi.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Matthieu Gallien <matthieu_gallien@yahoo.fr>"
SPDX-License-Identifier = "AGPL-3.0-or-later"


[[annotations]]
path = ["img/app.svg", "img/app-dark.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018-2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"
